/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.dao.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import com.edusys.dao.ui.quanly;

/**
 *
 * @author asus
 */
//public class ChaoJDialog extends javax.swing.JFrame implements Runnable{
//
//    Timer t;
//    int s = 0;
//    Thread th ;
//    
//    
//    public ChaoJDialog() {     
//        initComponents();
//        setLocationRelativeTo(null);
//        th = new Thread((Runnable)this);
//        
//        th.start();
//        
//        //cachs 2
////          t = new Timer(1000, new ActionListener() {
////            @Override
////            public void actionPerformed(ActionEvent ae) {
////                int value = jProgressBar1.getValue() + 1;
////                jProgressBar1.setValue(value <= 100 ? value : 0);
////            }
////        });
////          run();
//    }
//    
//    public void run(){
//        try {
//            for (int i = 1; i <=200; i++) {
//                s = s+1;
//                int m = jProgressBar1.getMaximum();
//                int v = jProgressBar1.getValue();
//                if(v<m){
//                    jProgressBar1.setValue(jProgressBar1.getValue()+1);
//                }else{
//                    i = 201;
//                    setVisible(false);
//                    DangNhapJFrame lg = new DangNhapJFrame();
//                    lg.setVisible(true);
//                }
//                
//                Thread.sleep(50);
//                
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//    }

public class ChaoJDialog extends javax.swing.JFrame {

    
    public ChaoJDialog() {
       
        initComponents();
         intit();
        
        
      
    }

   String check="";
 
     void intit(){
            new Timer(50, new ActionListener() {
            @Override
            
            public void actionPerformed(ActionEvent e) {
              
                setLocationRelativeTo(null); 
                int value = jProgressBar1.getValue();
                int a=0;
               
                if (value < 100) {
                    jProgressBar1.setValue(value + 1);
                    a=value+1;
                    lbln.setText(a+"%");
                     

                    if(value<30){
                        lblload.setText("Hệ thống quản lý đào tạo");
                    }else{
                        lblload.setText("Mã nhân viên là tên đăng nhập");
                    }if(value>60){
                        lblload.setText("Hệ thống dành cho Admin!");
                    }
                    if(value>90){
                        lblload.setText("Sẵn sàng để bắt đầu! wellcom");
                     
                    }
                }else{
                    check+="Stop";     
                    checkwwin();
                    ChaoJDialog.this.dispose();
                         
                    }
                
            }
        }).start();
       checkwwin();
       
    }
     void checkwwin(){
          if(check.equals("Stop")){
            openWelcome();
        }
     }
     void openWelcome() {
        new quanly().setVisible(true);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lblload = new javax.swing.JLabel();
        lbln = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Screenshot (1572).png"))); // NOI18N

        jProgressBar1.setStringPainted(true);

        lblload.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblload.setText("Loading ");

        lbln.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbln.setForeground(new java.awt.Color(255, 51, 51));
        lbln.setText("0%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(lblload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbln)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblload)
                    .addComponent(lbln))
                .addGap(32, 32, 32)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChaoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChaoJDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblload;
    private javax.swing.JLabel lbln;
    // End of variables declaration//GEN-END:variables
}
